# Seeking Chat Bot Configuration
app:
  name: "SeekingChatBot"
  version: "2.0.0"
  environment: "development"  # development, staging, production
  debug: true
  secret_key: "${SECRET_KEY}"
  
browser:
  headless: true
  window_size: [1920, 1080]
  user_agent_rotation: true
  fingerprint_spoofing: true
  
selenium:
  driver: "chrome"  # chrome, firefox, edge
  options:
    - "--disable-blink-features=AutomationControlled"
    - "--exclude-switches=enable-automation"
    - "--use-fake-ui-for-media-stream"
    - "--disable-dev-shm-usage"
    - "--no-sandbox"
    - "--disable-gpu"
    
anti_detection:
  use_proxies: true
  proxy_rotation_interval: 300  # seconds
  mouse_movement: true
  typing_simulation: true
  random_delays:
    min: 2
    max: 8
  human_behavior:
    scroll_randomly: true
    move_mouse_randomly: true
    random_click_delays: true
    
ai:
  provider: "grok"  # grok, openai, anthropic
  api_key: "${GROK_API_KEY}"
  model: "grok-1"
  temperature: 0.7
  max_tokens: 150
  context_window: 4000
  
response_strategy:
  use_templates: true
  use_ai: true
  template_weight: 0.3  # 30% templates, 70% AI
  context_management:
    strategy: "sliding_window"  # sliding_window, multi_agent
    window_size: 10
    include_profile_context: true
    
rate_limiting:
  messages_per_hour: 20
  messages_per_day: 100
  cooldown_between_messages: 30  # seconds
  business_hours_only: false
  business_hours:
    start: "09:00"
    end: "22:00"
    timezone: "America/New_York"
    
safety:
  bot_disclosure:
    enabled: true
    message: "Hi! Just so you know, I'm using an assistant to help manage my messages."
    frequency: "first_message"  # first_message, every_n_messages, never
  auto_stop:
    after_messages: 50
    after_hours: 2
    on_suspicious_activity: true
  blacklist:
    keywords: ["scam", "money", "gift card", "emergency"]
    users: []
    
database:
  url: "${DATABASE_URL}"
  pool_size: 20
  max_overflow: 40
  echo: false
  
redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  
monitoring:
  sentry_dsn: "${SENTRY_DSN}"
  prometheus_enabled: true
  log_level: "INFO"
  log_file: "logs/seeking_bot.log"
  
security:
  encryption_key: "${ENCRYPTION_KEY}"
  jwt_secret: "${JWT_SECRET}"
  session_timeout: 3600
  max_login_attempts: 5
  
deployment:
  platform: "heroku"  # heroku, aws, gcp
  workers: 4
  threads: 2
  timeout: 30